# Generated by Django 4.1 on 2023-07-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gado', '0003_lote_remove_animal_numero_lote_animal_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gado.lote'),
        ),
    ]
