# Generated by Django 4.1 on 2023-07-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gado', '0008_alter_cliente_bairro_alter_cliente_celular_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
    ]
