# Generated by Django 4.1 on 2023-07-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gado', '0010_alter_fornecedor_bairro_alter_fornecedor_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
