# Generated by Django 4.1 on 2023-07-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gado', '0012_caracteristica_animal_caracteristica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gado.cliente'),
        ),
    ]
