# Generated by Django 4.1 on 2023-07-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gado', '0014_remove_animal_campo2_remove_animal_campo3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='lote',
        ),
    ]
