# Generated by Django 4.1 on 2023-07-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gado', '0015_remove_animal_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='campo1',
            new_name='campo',
        ),
    ]
