# Generated by Django 4.1 on 2023-08-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gado', '0016_rename_campo1_animal_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='tipo',
        ),
    ]
